### ISSUE TITLE
As a User, I need the ability to post a picture (with a text description)

### ISSUE THREAD

**Issue by Lucas-ConU** [hakimsheriff/SOEN341Project#1]
**Description:** 
Users should be post a picture
**Steps:**
-allow user to upload a picture
-ask user for a caption
**Priority:**
Medium

**Comment by Lucas-ConU** [comment]
Core feature

**Comment by seaiam** [comment]
Users can now upload a picture with caption

**Comment by hakimsheriff** [comment]
Acceptance test for this feature:

- [ ]  Have a button clearly identifiable to begin posting a picture

- [ ] Click the button which will bring you to a page where you can enter post details  

- [ ] Enter description and tags. 

- [ ] Upload your image

- [ ] Click post

- [ ] Verify that your image shows up in main feed

This was tested and all aspects are functioning as expected.
