### ISSUE TITLE
As a User, I want to follow another user

### ISSUE THREAD

**Issue by seaiam** [hakimsheriff/SOEN341Project#2]
**Description:** 
Users should be able to follow other users in order to see their posts, users should be registered already
**Steps:**
-add first user to the second users's list of followers
-add second user to the first users' following list
-allow first user to see second users' post
**Priority:**
medium , we first need to register users before doing this

**Comment by Lucas-ConU** [comment]
Core feature

**Comment by seaiam** [comment]
Description: Users should be able to follow other users in order to see their posts, users should be registered already
Steps: 
-add first user to the second users's list of followers
-add second user to the first users' following list
-allow first user to see second users' post
Priority:
medium , we first need to register users before doing this

**Comment by hakimsheriff** [comment]
Acceptance test for this feature

- [ ] Login to website
- [ ] Find the user you would like to follow
- [ ] Click the follow button
- [ ] Verify that the follower counter for that user has incremented
- [ ] Return to your feed
- [ ] Verify that you see that users posts on your feed
- [ ] Return to the user you have followed
- [ ] Click the unfollow button
- [ ] Verify that the follower count has decremented
- [ ] Return to your feed
- [ ] Verify that you do not see that users posts on your feed
