### ISSUE TITLE
As a User, I want to comment on another post

### ISSUE THREAD

**Issue by Ahmad-ConU** [hakimsheriff/SOEN341Project#3]
**Description:**
Users should be able to comment on other user's posts
**Steps:**
-ask user for a comment
-save comment to the picture
**Priority:**
Medium

**Comment by Lucas-ConU** [comment]
Core feature

**Comment by hakimsheriff** [comment]
Acceptance test for this feature:

- [ ] On the main feed page, decide which post we want to leave a comment for and click the comment button
- [ ] On the post page, enter comment in text box and click comment
- [ ] Verify that comment is visible on post page
- [ ] Return to main feed and verify that comment counter has incremented

This test has been completed and all aspects are functioning as expected.
